### ISSUE TITLE
Script not working in Fall Creator's Update

### ISSUE THREAD

**Issue by JingYenLoh** [Ciantic/DisableFlashingTaskbarButtons#2]
Hello, I recently (auto-)updated to Windows 10 Fall Creator's (Build 17134.48) and the script is no longer working. When I try to execute it, it gives the following Msg:

![image](https://user-images.githubusercontent.com/22059033/39870974-d45f1542-5495-11e8-9f67-d0fbcff0edca.png)

Is there any way I can debug this? I would be happy to make a pull request 😄

**Comment by Ciantic** [comment]
It's fixed! I think you must be first one using this besides me 👍 

P.S. Debugging autohotkey is not on option really, it requires to debug Explorer.exe with X64Dbg and disasssemble that. I just did that in Hyper-V Virtual Machine, looks like she SHELLHOOK had changed from C02B to C028.
