### ISSUE TITLE
"Can't find empty area for the patch :("

### ISSUE THREAD

**Issue by UsernameIsAlreadyTakenByMe** [Ciantic/DisableFlashingTaskbarButtons#5]
Hi,

I just would like to mention that the latest patch (8dfb574) works with latest Windows 10 22H2 (19045.5011, 10/2024)
an earlier patch worked with (07a46b5) Windows 10 1809 (build 17763.737)
and and old patch (debf825) worked before Windows 10 1809

Br,
Zoltan

**Comment by UsernameIsAlreadyTakenByMe** [comment]
Hi,
I don't know which Windows update has broken it again... but the issue is back. Could you help, please? :)

**Comment by n00bator** [comment]
Hi,

same here. Help, please. Can't live with constant taskbar flashing.

One of those Windows 10 updates must have broken this script:
 - Security Update for Microsoft Windows (KB5044273)
 - Update for Microsoft Windows (KB5044029)
 - Servicing Stack 10.0.19041.4950

**Comment by n00bator** [comment]
It looks like Update for Microsoft Windows (KB5044029) and/or (KB5044273) breaks DisableFlashingTaskbarButtons.

**Comment by glagla00** [comment]
is there any fix for this

**Comment by Ciantic** [comment]
Did any of you try the fix in this: 

https://github.com/Ciantic/DisableFlashingTaskbarButtons/pull/7/files

I don't have Window 10 anymore, it's hard to try. I guess I could try with some Hyper-V image.

**Comment by Ciantic** [comment]
I merged the pull request, I don't have way to verify, but hope it works?

**Comment by UsernameIsAlreadyTakenByMe** [comment]
Thank you! The fix works :)
